import Head from 'next/head'
import Image from 'next/image'
import Sidebar from '../components/Sidebar'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Spotify-clon</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main className='bg-black h-screen overflow-hidden'>
        <Sidebar/>
      </main>
    </div>
  )
}
